import React from "react";
import { Metadata } from "next";
import OdishaOutlets from "./OdishaOutlets";


// Server-side metadata export
export const metadata: Metadata = {
  title:
    "Odisha Outlets - Sky automobile Motors, Maruti Suzuki, Monsoon offers, Special Offers, September month offers",
  description: "Generated by create next app",
};

const ODOutlets = () => {
  return <OdishaOutlets />;
};

export default ODOutlets;
