import VehicleDetailTemplate from "@/components/others/VehicleDetailTemplate";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Maruti Alto 800 On Road Price",
  description: "Generated by create next app",
};
const Alto800: React.FC = () => {
  return (
    <div>
      <VehicleDetailTemplate index={0} />
    </div>
  );
};

export default Alto800;
