import VehicleDetailTemplate from "@/components/others/VehicleDetailTemplate";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Maruti Invicto On Road Price",
  description: "Generated by create next app",
};
const Invicto: React.FC = () => {
  return (
    <div>
      <VehicleDetailTemplate index={9} />
    </div>
  );
};

export default Invicto;
