import VehicleDetailTemplate from "@/components/others/VehicleDetailTemplate";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Maruti Grand Vitara On Road Price In Bhubaneswar",
  description: "Generated by create next app",
};
const GrandVitara: React.FC = () => {
  return (
    <div>
      <VehicleDetailTemplate index={12} />
    </div>
  );
};

export default GrandVitara;
