
import { Metadata } from "next";
import ContactUs from "./ContactUs";


// Server-side metadata export
export const metadata: Metadata = {
  title:
    "Contact Us -Sky automobile Motors, Maruti Suzuki, Monsoon offers, Special Offers, September month offers",
  description: "Generated by create next app",
};


export default function ContactUsPage() {
  return <ContactUs />;
}
