
import Footer from "@/components/others/Footer";
import Header from "@/components/others/Header";
import { Metadata } from "next";
import React from "react";
import AboutUs from "./AboutUs";

export const metadata: Metadata = {
  title: "About us - Sky automobile Motors, Maruti Suzuki",
  description: "Generated by create next app",
};

const AboutUsPage = () => {

  return (
    <div className="min-h-screen">
      <Header />
     <AboutUs />
      <Footer />
    </div>
  );
};

export default AboutUsPage;
