import VehicleDetailTemplate from "@/components/others/VehicleDetailTemplate";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Maruti Dzire On Road Price In Bhubaneswar",
  description: "Generated by create next app",
};
const Dzire: React.FC = () => {
  return (
    <div>
      <VehicleDetailTemplate index={3} />
    </div>
  );
};

export default Dzire;
