import VehicleDetailTemplate from "@/components/others/VehicleDetailTemplate";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Maruti Ertiga On Road Price In Raipur",
  description: "Generated by create next app",
};
const Ertiga: React.FC = () => {
  return (
    <div>
      <VehicleDetailTemplate index={6} />
    </div>
  );
};

export default Ertiga;
