import React from 'react'
import { Metadata } from "next";
import ChhattisgarhOutlets from './ChhattisgarhOutlets';

// Server-side metadata export
export const metadata: Metadata = {
  title:
    "Chhattisgarh Outlets - Sky automobile Motors, Maruti Suzuki, Monsoon offers, Special Offers, September month offers",
  description: "Generated by create next app",
};

const CGOutlets = () => {
 return <ChhattisgarhOutlets />
}

export default CGOutlets;