import VehicleDetailTemplate from "@/components/others/VehicleDetailTemplate";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Maruti Alto k10 On Road Price",
  description: "Generated by create next app",
};
const AltoK10: React.FC = () => {
  return (
    <div>
      <VehicleDetailTemplate index={0} />
    </div>
  );
};

export default AltoK10;
