import VehicleDetailTemplate from "@/components/others/VehicleDetailTemplate";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Maruti Ecco On Road Price In Bhubaneswar",
  description: "Generated by create next app",
};
const Ecco: React.FC = () => {
  return (
    <div>
      <VehicleDetailTemplate index={8} />
    </div>
  );
};

export default Ecco;
