import VehicleDetailTemplate from "@/components/others/VehicleDetailTemplate";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Maruti Wagon R On Road Price In Bhubaneswar",
  description: "Generated by create next app",
};
const WagonR: React.FC = () => {
  return (
    <div>
      <VehicleDetailTemplate index={5} />
    </div>
  );
};

export default WagonR;
