
import { Metadata } from "next";
import BuyACar from "./BuyACar";


// Server-side metadata export
export const metadata: Metadata = {
  title:
    "Buy Your Car - Sky automobile Motors, Maruti Suzuki, Monsoon offers, Special Offers, September month offers",
  description: "Generated by create next app",
};

export default function BookAServicePage() {
  return <BuyACar />;
}
