import VehicleDetailTemplate from "@/components/others/VehicleDetailTemplate";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Maruti Ignis On Road Price",
  description: "Generated by create next app",
};
const Ignis: React.FC = () => {
  return (
    <div>
      <VehicleDetailTemplate index={15} />
    </div>
  );
};

export default Ignis;
