
import { Metadata } from "next";
import CareerPage from "./CareerPage";


// Server-side metadata export
export const metadata: Metadata = {
  title:
    "Career - Sky automobile Motors, Maruti Suzukii",
  description: "Generated by create next app",
};


export default function Career() {
  return <CareerPage />;
}
