import VehicleDetailTemplate from "@/components/others/VehicleDetailTemplate";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Maruti Spresso On Road Price In Bhubaneswar",
  description: "Generated by create next app",
};
const Spresso: React.FC = () => {
  return (
    <div>
      <VehicleDetailTemplate index={4} />
    </div>
  );
};

export default Spresso;
