import VehicleDetailTemplate from "@/components/others/VehicleDetailTemplate";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Maruti Ciaz On Road Price",
  description: "Generated by create next app",
};
const Ciaz: React.FC = () => {
  return (
    <div> 
      <VehicleDetailTemplate index={13} />
    </div>
  );
};

export default Ciaz;
