// pages/offers.tsx
import { Metadata } from "next";
import Finance from "./Finance";


// Server-side metadata export
export const metadata: Metadata = {
  title:
    "Finance - Sky automobile Motors, Maruti Suzuki, Monsoon offers, Special Offers, September month offers",
  description: "Generated by create next app",
};


export default function FinancePage() {
  return <Finance />;
}
