// pages/offers.tsx
import { Metadata } from "next";
import Insurance from "./Insurance";



// Server-side metadata export
export const metadata: Metadata = {
  title:
    "Insurance - Sky automobile Motors, Maruti Suzuki, Monsoon offers, Special Offers, September month offers",
  description: "Generated by create next app",
};


export default function InsurancePage() {
  return <Insurance />;
}
