import VehicleDetailTemplate from "@/components/others/VehicleDetailTemplate";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Maruti Brezza On Road Price",
  description: "Generated by create next app",
};
const Brezza: React.FC = () => {
  return (
    <div>
      <VehicleDetailTemplate index={2} />
    </div>
  );
};

export default Brezza;
