// pages/offers.tsx
import { Metadata } from "next";
import Offers from "./Offers";

// Server-side metadata export
export const metadata: Metadata = {
  title:
    "Sky automobile Motors, Maruti Suzuki, Monsoon offers, Special Offers, September month offers",
  description: "Generated by create next app",
};

// Default export for the Offers page, can be a server component
export default function OffersPage() {
  return <Offers />;
}
